apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - externalsecret.yaml
  - serviceaccount.yaml
  - pvc.yaml

configMapGenerator:
  - name: rss-discord-bot
    files:
      - files/config.yaml
      - files/main.py
      - files/bot.py
      - files/config.py
      - files/discord_handlers.py
      - files/rss.py
      - files/state.py
