apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: foundry-vtt

resources:
  - base

commonLabels:
  platform: foundry-vtt

labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/part-of: "foundry-vtt"
