apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - externalsecret.yaml
  - serviceaccount.yaml
  - pvc.yaml

configMapGenerator:
  - name: actor-bot
    files:
      - files/bot.py
