apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - externalsecret.yaml
  - pvc.yaml
  - service.yaml
  - statefulset.yaml

labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/name: "foundry-vtt"
