apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - foundry-vtt
  - filebrowser
  - cloudflared

labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/component: "base"
