apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - statefulset.yaml
  - service.yaml
  - command-bridge-service.yaml
  - pvc.yaml
  - configmap-machine-id.yaml
  - externalsecret-command-bridge.yaml
  - cronjob.yaml
  - role.yaml
  - rolebinding.yaml
  - serviceaccount.yaml

labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/name: "hytale-server"
