apiVersion: v1
kind: Service
metadata:
  name: hytale-server
  annotations:
    service.cilium.io/loadbalancer-ipam-ips: "10.70.30.205"
spec:
  type: LoadBalancer
  loadBalancerIP: 10.70.30.205
  selector:
    app: hytale-server
  ports:
  - name: hytale-udp
    port: 5520
    targetPort: 5520
    protocol: UDP
