apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - rss-discord-bot
  - rss-parser
  - actor-bot

labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/component: "base"
