apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - externalsecret.yaml

configMapGenerator:
  - name: hytale-discord-bot
    files:
      - bot.py

generatorOptions:
  disableNameSuffixHash: true
