apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - externalsecret.yaml

configMapGenerator:
- name: cloudflared-config-cm
  files:
    - ./config/config.yaml

labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/name: "cloudflared"
