apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - plex
  - vpn-qbittorrent
  - radarr
  - prowlarr
  - lidarr
  - sonarr
  - plex-auto-languages
  - bazarr
  - cloudflared
  - overseerr

labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/component: "base"
