apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - externalsecret.yaml
  - service.yaml
  - statefulset.yaml
  - job.yaml
  - pvc.yaml
  - role.yaml
  - rolebinding.yaml
  - serviceaccount.yaml

labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/name: "plex"
