apiVersion: v1
kind: Service
metadata:
  name: plex-media-server
  annotations:
    service.cilium.io/global: "true"
    service.cilium.io/loadbalancer-ipam-ips: "10.70.30.201"
spec:
  selector:
    app: plex
  ports:
    - name: http
      protocol: TCP
      port: 32400
      targetPort: 32400
      nodePort: 32400 
  type: LoadBalancer
  loadBalancerIP: 10.70.30.201
