apiVersion: v1
kind: Service
metadata:
  name: plex-media-server
  annotations:
    service.cilium.io/global: "true"
spec:
  selector:
    app: plex
  ports:
    - protocol: TCP
      port: 32400
  type: LoadBalancer

